/* CARDS */
export const PLAY = "PLAY";
export const PLAY_SUCCESS = "PLAY_SUCCESS";
export const START_GAME = "START_GAME";
export const START_GAME_SUCCESS = "START_GAME_SUCCESS";
export const SET_CARDS = "SET_CARDS";

/* FORM */
export const SET_USERNAME = "SET_USERNAME";
export const SET_USERNAME_SUCCESS = "SET_USERNAME_SUCCESS";

/* RANKING */
export const FETCH_RANKING = "FETCH_RANKING";
export const FETCH_RANKING_SUCCESS = "FETCH_RANKING_SUCCESS";
export const PUSH_TO_RANKING = "PUSH_TO_RANKING";
export const PUSH_TO_RANKING_SUCCESS = "PUSH_TO_RANKING_SUCCESS";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_MODAL_SUCCESS = "TOGGLE_MODAL_SUCCESS";
